#!/usr/bin/env bash

CACHE="$(dirname $0)/.cache/bugs"

if [ "$#" -ne 1 ]; then
  (cd $(npm prefix) && npm bugs)
elif [[ "$1" =~ ^[^@].+/.+ ]]; then
  open https://github.com/$1/issues
else
  if [ ! -e "$CACHE/$1" ]; then
    mkdir -p $(dirname "$CACHE/$1")
    npm view "$1" bugs.url > "$CACHE/$1"
    echo Added "$1" to cache.
  else
    echo Using cache: $(< "$CACHE/$1")
  fi
  open $(< "$CACHE/$1")
fi
