#!/usr/bin/env node

var exec = require('child_process').exec

var portList = process.argv.slice(2)
  .filter(function (arg) { return /^\d+$/.test(arg) })
  .map(function (port) { return '-i :' + port })
  .join(' ')

exec('lsof -t ' + portList, function (error, stdout, stderr) {
  process.stdout.write(stdout)
  process.stderr.write(stderr)

  if (!stdout.trim()) {
    console.error('No processes found')
    process.exit(1)
  }

  var pidList = stdout.split(/\s+/).join(' ')

  var killArgs = process.argv.slice(2)
    .filter(function (arg) { return arg.startsWith('-') })
    .join(' ')

  var killCommand = 'kill ' + killArgs + ' ' + pidList
  exec(killCommand, function (error, stdout, stderr) {
    if (error && error.code) process.exit(error.code)
    if (error && error.signal) process.kill(process.pid, error.signal)
    process.stdout.write(stdout)
    process.stderr.write(stderr)
  })
})
