#!/bin/bash

# Script to convert PDF file to JPG images
#
# Dependencies:
# * ghostscript
# * imagemagick

for PDF in "$@"
do
  echo "Processing $PDF..."
  DIR=`basename "$PDF" .pdf`

  mkdir "$DIR"

  gs -dUseCropBox -dAutoRotatePages=/None -sDEVICE=jpeg -dJPEGQ=75 -r150 -o "$DIR"/%04d.jpg "$PDF"
done
